name: shell commands

on: [push]

jobs:
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: 
          node -v
          npm -v
      - name: python command
        run:
          import platform
          platform.processor()
        shell: python
  run-shell-commands:
      runs-on: windows-latest
      steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory bash
        run: pwd
        shell: bash