name: shell commands

on: [push]

jobs:
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: 
          node -v
          npm -v
      - name: directory powershell
        run: Get-Location
      - name: Directory bash
        run: pwd
        shell: bash